version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.5

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Docker build
          command: |
            sudo docker build -t ${IMG_NAME} .
      
      - run:
          name: Run Docker image and test
          command: |
            docker run --rm -d -p 80:80 --name weather_app ${IMG_NAME}
            python3 --version
            python3 unitest.py

      - run:
          name: Run Tests
          command: |
            pip install selenium
            python3 selenium_location.py
